# specify the node base image with your desired version
FROM node:16

# replace this with your application's default port
EXPOSE 8888

# Your app setup here

ENV NODEJS_VERSION =16 \
    HOME="/home/nodejs"

