FROM registry.access.redhat.com/rhscl/mysql-57-rhel7

MAINTAINER username <andry@optimacomputer.com>

ENV $MYSQL_USER=user1 $MYSQL_PASSWORD=mypa55 $MYSQL_DATABSE=items $MYSQL_ROOT_PASSWORD=r00tpa55

ADD root/ /root
